project 'MyFirebaseApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFirebaseApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFirebaseApp
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseUI'

  target 'MyFirebaseAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyFirebaseAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
